package com.example.imageprocessing.services;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import com.example.imageprocessing.entities.User;
import com.example.imageprocessing.repositories.UserRepository;

@Component
public class UserService implements UserDetailsService{

  @Autowired
  private PasswordEncoder passwordEncoder;

  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  public User registerUser(User userObj) {
    userObj.setPassword(passwordEncoder.encode(userObj.getPassword()));
    userRepository.save(userObj);

    return userObj;
  }

  public boolean existsByEmail(String email) {
    return userRepository.existsByEmail(email);
  }

  public User loadUserByEmail(String email) {
    User userRecord = userRepository.findByEmail(email);

    if (userRecord == null) {
      throw new UsernameNotFoundException("User Not Found with username: " + email);
    }

    return userRecord;
  }

  @Override
  public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
    User userRecord = userRepository.findByEmail(username);

    if (userRecord == null) {
      throw new UsernameNotFoundException("User Not Found with username: " + username);
    }

     return new org.springframework.security.core.userdetails.User(
                userRecord.getEmail(),
                userRecord.getPassword(), // should be encoded
                new ArrayList<>()
        );
  }

}
