spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-id>
            client-secret: <client-secret>

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG