spring.application.name=mcpdemo
spring.main.web-application-type=none
spring.ai.mcp.server.version=0.0.1

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
spring.main.banner-mode=off
logging.level.org.springframework.ai.mcp=DEBUG
# logging.pattern.console=

# Ollama local configuration
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.chat.model=phi3:mini
spring.ai.ollama.chat.system-prompt=You are an AI assistant with access to tools. Always use the appropriate tool when available, and return arguments in JSON.
